### ISSUE TITLE
Fix dependencies to specific versions

### ISSUE THREAD

**Issue by mpbrown** [CodeForBuffalo/affordable_water#18]
Django 3.0 update resulted in many packages breaking. See [ImportError](https://github.com/adamchainz/django-cors-headers/issues/366).

- [ ] Go through python packages in Pipfile and find the package(s) that broke and see what the status is on fixes.

- [ ] Update Pipfile to use specific version instead of latest (*).

**Comment by mpbrown** [comment]
@truffi01 Are these errors still coming up when you start the server on your local machine? I just updated the Pipfile to use Django 2.2.8 instead of latest (3.x) and so far haven't run into `import six` issues including on the latest [Travis CI build](https://travis-ci.com/CodeForBuffalo/affordable_water/builds/142264529)

**Comment by truffi01** [comment]
Yes. I get a 500 error.
